version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
      POSTGRES_DB: qa_test_management
    ports:
      - "5432:5432"
    volumes:
      - qa_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  qa_pg_data:
